# Step 1: Build Stage
FROM node:18 AS build-stage

# 작업 디렉토리 설정
WORKDIR /app

# package.json 및 package-lock.json 복사
COPY package*.json ./

# 의존성 설치
RUN npm install

# 소스 코드 복사
COPY . .

# Vue 애플리케이션 빌드
RUN npm run build

# Step 2: Production Stage
FROM nginx:alpine AS production-stage

# 빌드된 파일을 Nginx의 기본 웹 루트로 복사
COPY --from=build-stage /app/dist /usr/share/nginx/html

# 포트 설정 (기본적으로 80 포트를 사용)
EXPOSE 5173

# Nginx 실행
CMD ["nginx", "-g", "daemon off;"]
